### ISSUE TITLE
missing a required aargument: 'units'

### ISSUE THREAD

**Issue by amanm6925** [Chinmayrane16/Depression-Chatbot#3]
Getting this error on running app.py

Traceback (most recent call last):
  File "/home/aman/anaconda3/lib/python3.6/inspect.py", line 2842, in _bind
    arg_val = next(arg_vals)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aman/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/aman/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/aman/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aman/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aman/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aman/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aman/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aman/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aman/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aman/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aman/Desktop/NLP_chatbot/Depression-Chatbot-master/Deploy Flask/app.py", line 213, in index
    bot_response = respond(sentence)
  File "/home/aman/Desktop/NLP_chatbot/Depression-Chatbot-master/Deploy Flask/app.py", line 151, in respond
    model = BasicS2SModel(vocab=vocab,mode="inference",use_beam_search=False,num_layers=3)
  File "/home/aman/Desktop/NLP_chatbot/Depression-Chatbot-master/Deploy Flask/model.py", line 122, in __init__
    self.setup_attention_decoder()
  File "/home/aman/Desktop/NLP_chatbot/Depression-Chatbot-master/Deploy Flask/model.py", line 255, in setup_attention_decoder
    name = "BahdanauAttention"
  File "/home/aman/anaconda3/lib/python3.6/site-packages/typeguard/__init__.py", line 889, in wrapper
    memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
  File "/home/aman/anaconda3/lib/python3.6/site-packages/typeguard/__init__.py", line 110, in __init__
    self.arguments = signature.bind(*args, **kwargs).arguments
  File "/home/aman/anaconda3/lib/python3.6/inspect.py", line 2965, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/home/aman/anaconda3/lib/python3.6/inspect.py", line 2880, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'units'

**Comment by JyotsnaBhuwad** [comment]
I am getting the same error . did u solve the error; if yes plz help me.
